// Généré par tauri-specta — ne pas modifier.
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Ouvre un document. Sans mot de passe, essaie celui mémorisé dans le trousseau.
	 *  `remember` mémorise le mot de passe fourni s'il est correct.
	 */
	openDocument: (path: string, password: string | null, remember: boolean) => typedError<DocInfo, PdfError>(__TAURI_INVOKE("open_document", { path, password, remember })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	closeDocument: (doc: number) => __TAURI_INVOKE<void>("close_document", { doc }),
	/**  Abandonne les rendus en attente d'une époque antérieure (défilement rapide, zoom). */
	setRenderEpoch: (doc: number, epoch: number) => __TAURI_INVOKE<void>("set_render_epoch", { doc, epoch }),
	getOutline: (doc: number) => typedError<OutlineItem[], PdfError>(__TAURI_INVOKE("get_outline", { doc })),
	/**  Modèle d'annotations du document (chargé à la demande). */
	loadAnnotations: (doc: number) => typedError<EditState, PdfError>(__TAURI_INVOKE("load_annotations", { doc })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.data.pages==null?v.data.pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	/**  Applique des opérations (ajout, modification, suppression) en une seule étape d'annulation. */
	applyAnnotations: (doc: number, ops: AnnotOp[]) => typedError<EditState, PdfError>(__TAURI_INVOKE("apply_annotations", { doc, ops })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.data.pages==null?v.data.pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	/**
	 *  Opération sur les pages (déplacement, rotation, suppression, duplication, page blanche,
	 *  copie depuis un autre document), en une étape d'annulation.
	 */
	applyPages: (doc: number, op: PageOp) => typedError<EditState, PdfError>(__TAURI_INVOKE("apply_pages", { doc, op })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.data.pages==null?v.data.pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	/**  Enregistre les pages choisies dans un nouveau PDF. */
	extractPages: (doc: number, pages: number[], path: string) => typedError<null, PdfError>(__TAURI_INVOKE("extract_pages", { doc, pages, path })),
	/**  Exporte le document (planche 10) ; renvoie les fichiers écrits. */
	exportDocument: (doc: number, opts: ExportOptions, path: string) => typedError<ExportResult, PdfError>(__TAURI_INVOKE("export_document", { doc, opts, path })),
	/**  Taille estimée d'un export PDF (rien n'est écrit). */
	exportEstimate: (doc: number, opts: ExportOptions) => typedError<ExportResult, PdfError>(__TAURI_INVOKE("export_estimate", { doc, opts })),
	/**  Imprime le document (dialogue d'impression du système) ; vrai si l'impression est lancée. */
	printDocument: (doc: number, name: string, pages: ([number, number])[]) => typedError<boolean, PdfError>(__TAURI_INVOKE("print_document", { doc, name, pages: pages.map(i=>i) })),
	/**  Copie figée de pages (presse-papiers de pages) : document en mémoire à coller ailleurs. */
	clipPages: (doc: number, pages: number[]) => typedError<DocInfo, PdfError>(__TAURI_INVOKE("clip_pages", { doc, pages })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	/**
	 *  Ouvre un PDF comme source de pages (fichier déposé sur les miniatures), sans l'ajouter aux
	 *  documents récents. À fermer avec `close_document`.
	 */
	openPageSource: (path: string) => typedError<DocInfo, PdfError>(__TAURI_INVOKE("open_page_source", { path })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	undo: (doc: number) => typedError<EditState, PdfError>(__TAURI_INVOKE("undo", { doc })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.data.pages==null?v.data.pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	redo: (doc: number) => typedError<EditState, PdfError>(__TAURI_INVOKE("redo", { doc })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.data.pages==null?v.data.pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	/**  Masque une annotation pendant son édition en place (hors historique). */
	setAnnotationHidden: (doc: number, id: string, hidden: boolean) => typedError<EditState, PdfError>(__TAURI_INVOKE("set_annotation_hidden", { doc, id, hidden })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.data.pages==null?v.data.pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	/**  Boîtes des lignes de texte entre deux points (outils de marquage). */
	textRange: (doc: number, page: number, from: Point, to: Point) => typedError<TextSelection, PdfError>(__TAURI_INVOKE("text_range", { doc, page, from, to })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,rects:v.data.rects.map(i=>i)}) } : v) as typeof v)),
	importImage: (doc: number, path: string) => typedError<ImageInfo, PdfError>(__TAURI_INVOKE("import_image", { doc, path })),
	/**  Copie une image importée d'un document à l'autre (collage d'un tampon image). */
	copyImage: (from: number, to: number, key: string) => typedError<null, PdfError>(__TAURI_INVOKE("copy_image", { from, to, key })),
	/**  Image PNG ou JPEG produite par l'interface (signature manuscrite). */
	importImageBytes: (doc: number, bytes: number[]) => typedError<ImageInfo, PdfError>(__TAURI_INVOKE("import_image_bytes", { doc, bytes })),
	/**  Octets d'une image choisie par l'utilisateur (onglet « Importer » d'une signature). */
	readImageFile: (path: string) => typedError<number[], PdfError>(__TAURI_INVOKE("read_image_file", { path })),
	listSignatures: () => __TAURI_INVOKE<SavedSignature_Serialize[]>("list_signatures").then((v) => (v.map(i=>i) as typeof v)),
	saveSignature: (png: number[], width: number, height: number) => typedError<SavedSignature_Serialize, PdfError>(__TAURI_INVOKE("save_signature", { png, width, height })),
	deleteSignature: (id: string) => typedError<null, PdfError>(__TAURI_INVOKE("delete_signature", { id })),
	/**
	 *  Enregistre le document (sur place, ou sous `path`). Écriture atomique ; l'original n'est
	 *  jamais touché avant cet appel.
	 */
	saveDocument: (doc: number, path: string | null) => typedError<DocInfo, PdfError>(__TAURI_INVOKE("save_document", { doc, path })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	getLinks: (doc: number, page: number) => typedError<LinkInfo[], PdfError>(__TAURI_INVOKE("get_links", { doc, page })),
	/**  Signatures numériques du document et résultat de leur vérification. */
	getSignatures: (doc: number) => typedError<SignatureInfo[], PdfError>(__TAURI_INVOKE("get_signatures", { doc })).then((v) => ((v.status === "ok" ? { ...v, data: v.data.map(i=>({...i,rect:i.rect==null?i.rect:i.rect,signedAt:i.signedAt==null?i.signedAt:i.signedAt,timestamp:i.timestamp==null?i.timestamp:i.timestamp,certificate:i.certificate==null?i.certificate:i.certificate})) } : v) as typeof v)),
	/**  Approuve l'autorité en haut de la chaîne de la signature `field`. */
	trustSignatureRoot: (doc: number, field: string) => typedError<TrustedRoot, PdfError>(__TAURI_INVOKE("trust_signature_root", { doc, field })),
	listTrustedRoots: () => __TAURI_INVOKE<TrustedRoot[]>("list_trusted_roots").then((v) => (v.map(i=>i) as typeof v)),
	trustListsInfo: () => __TAURI_INVOKE<TrustListsInfo>("trust_lists_info"),
	removeTrustedRoot: (id: string) => typedError<null, PdfError>(__TAURI_INVOKE("remove_trusted_root", { id })),
	getPageText: (doc: number, page: number) => typedError<PageText, PdfError>(__TAURI_INVOKE("get_page_text", { doc, page })),
	/**  Recherche plein texte ; les résultats arrivent page par page sur `on_event`. */
	search: (doc: number, searchId: number, query: string, caseSensitive: boolean, onEvent: Channel<SearchEvent>) => __TAURI_INVOKE<void>("search", { doc, searchId, query, caseSensitive, onEvent }),
	cancelSearch: (doc: number) => __TAURI_INVOKE<void>("cancel_search", { doc }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSettings: (settings: Settings) => typedError<null, PdfError>(__TAURI_INVOKE("set_settings", { settings })),
	getRecents: () => __TAURI_INVOKE<RecentDoc[]>("get_recents").then((v) => (v.map(i=>i) as typeof v)),
	removeRecent: (path: string) => typedError<null, PdfError>(__TAURI_INVOKE("remove_recent", { path })),
	clearRecents: () => typedError<null, PdfError>(__TAURI_INVOKE("clear_recents")),
	/**  Langue de l'OS (ex. « fr-FR »). */
	systemLocale: () => __TAURI_INVOKE<string>("system_locale"),
	/**  Fichiers passés en ligne de commande au lancement (vidé à la lecture). */
	takePendingFiles: () => __TAURI_INVOKE<string[]>("take_pending_files"),
	/**
	 *  Erreurs JavaScript de l'interface, recopiées dans le terminal (diagnostic sous WebKitGTK,
	 *  dont la console n'est pas visible).
	 */
	logFrontendError: (message: string) => __TAURI_INVOKE<void>("log_frontend_error", { message }),
	/**  Installation de l'agent (préférences). */
	aiDetect: (agent: Agent) => typedError<Detected, AiError>(__TAURI_INVOKE("ai_detect", { agent })),
	/**  Lance une demande ; le texte arrive par `AiChunkEvent`, le résultat complet à la fin. */
	aiRun: (requestId: string, task: AiTask) => typedError<string, AiError>(__TAURI_INVOKE("ai_run", { requestId, task })),
	aiCancel: (requestId: string) => __TAURI_INVOKE<void>("ai_cancel", { requestId }),
	/**  Informations mémorisées pour remplir les documents (préférences, panneau IA). */
	getAiMemory: () => __TAURI_INVOKE<string[]>("get_ai_memory"),
	/**  Remplace les informations mémorisées (doublons et lignes vides retirés). */
	setAiMemory: (facts: string[]) => typedError<string[], PdfError>(__TAURI_INVOKE("set_ai_memory", { facts })),
	/**  Thème d'Omarchy (Linux), s'il est installé. */
	getOmarchyTheme: () => __TAURI_INVOKE<{
	/**  Nom du thème (« tokyo-night »). */
	name: string,
	/**  Thème sombre (`mode`, ou absence de `light.mode`) ; `None` : à déduire du fond. */
	dark: boolean | null,
	/**  Couleurs de `colors.toml` (« #rrggbb »), par nom de clé. */
	colors: { [key in string]: string },
} | null>("get_omarchy_theme"),
};

/** Events */
export const events = {
	aiChunkEvent: makeEvent<AiChunkEvent>("ai-chunk-event"),
	aiEditedEvent: makeEvent<AiEditedEvent>("ai-edited-event", (v) => ({...v,state:({...v.state,annots:v.state.annots.map(i=>i),fields:v.state.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.state.pages==null?v.state.pages:v.state.pages.map(i=>i)})}), (v) => ({...v,state:({...v.state,annots:v.state.annots.map(i=>i),fields:v.state.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})})),pages:v.state.pages==null?v.state.pages:v.state.pages.map(i=>i)})})),
	aiMemoryEvent: makeEvent<AiMemoryEvent>("ai-memory-event"),
	aiToolEvent: makeEvent<AiToolEvent>("ai-tool-event"),
	omarchyThemeEvent: makeEvent<OmarchyThemeEvent>("omarchy-theme-event"),
	openFilesEvent: makeEvent<OpenFilesEvent>("open-files-event"),
	trustListsUpdatedEvent: makeEvent<TrustListsUpdatedEvent>("trust-lists-updated-event"),
};

/* Types */
export type Agent = "none" | "claude" | "codex";

/**  Morceau de réponse. */
export type AiChunkEvent = {
	requestId: string,
	delta: string,
};

/**  Le document a été modifié par l'agent : nouvel état d'édition de l'onglet. */
export type AiEditedEvent = {
	doc: number,
	state: EditState,
};

/**  Erreur d'une demande ; le front affiche le message traduit. */
export type AiError = {
	kind: AiErrorKind,
	detail: string,
};

export type AiErrorKind = "notConfigured" | "notFound" | "outdated" | "failed" | "cancelled" | "timeout";

/**  L'agent propose de mémoriser des informations : carte dans le panneau. */
export type AiMemoryEvent = {
	requestId: string,
	add: string[],
	/**  Informations déjà mémorisées que les nouvelles remplacent. */
	replace: string[],
};

/**  Tâche demandée par le front. */
export type AiTask = 
/**  Vérification depuis les préférences. */
{ kind: "test" } | 
/**  Question ou action sur le document ouvert. */
{ kind: "chat"; doc: number; name: string; 
/**  Taille des pages affichées (points). */
pages: ([number, number])[]; 
/**  Langue de l'interface (« fr », « en »). */
lang: string; history: ChatTurn[]; question: string };

/**  Appel d'outil par l'agent, pour montrer ce qu'il fait. */
export type AiToolEvent = {
	requestId: string,
	/**  Nom sans le préfixe MCP (`get_page_text`…). */
	name: string,
	/**  Arguments, en JSON. */
	input: string,
};

export type Annot = {
	/**  Identifiant stable (`/NM` si présent, sinon généré). */
	id: string,
	page: number,
	rect: Rect,
	/**  Couleur « #rrggbb ». */
	color: string,
	/**  Opacité 0–1 (`/CA`). */
	opacity: number,
	/**  Épaisseur du trait en points. */
	width: number,
	/**  Commentaire associé (`/Contents`). */
	contents: string | null,
	author: string | null,
	/**  Date de modification (`/M`, format PDF). */
	modified: string | null,
	/**  Texte recouvert (surlignage, soulignement…), calculé pour la liste. */
	excerpt: string | null,
	body: AnnotBody,
	/**  Masquée le temps d'une édition en place (jamais enregistrée). */
	hidden?: boolean,
};

export type AnnotBody = { type: "highlight"; quads: Rect[] } | { type: "underline"; quads: Rect[] } | { type: "strikeOut"; quads: Rect[] } | { type: "freeText"; text: string; font: FontFamily; size: number } | 
/**  Note (annotation /Text) : icône sur la page, texte dans `contents`. */
{ type: "note" } | { type: "square" } | { type: "circle" } | { type: "line"; from: Point; to: Point; arrow: boolean } | { type: "check"; style: CheckStyle } | 
/**  Tampon image ; `image` identifie l'image importée (ou l'apparence existante). */
{ type: "image"; image: string } | 
/**  Zone à caviarder : le contenu sous les zones est supprimé à l'enregistrement. */
{ type: "redact"; quads: Rect[] } | 
/**  Annotation existante non éditable (Ink, Polygon, tampon externe…) : déplacer ou supprimer. */
{ type: "other"; subtype: string };

/**  Opération élémentaire sur les annotations (pattern commande). */
export type AnnotOp = 
/**  `index` : position d'insertion (utilisée pour annuler une suppression). */
{ op: "add"; annot: Annot; index: number | null } | { op: "update"; annot: Annot } | { op: "remove"; id: string } | 
/**  Valeur d'un champ de formulaire (voir `FormField::value`). */
{ op: "setField"; id: string; value: string[] };

export type CalcOp = "sum" | "product" | "average" | "min" | "max";

/**  `AFSimple_Calculate`. */
export type Calculation = {
	op: CalcOp,
	/**  Noms de champs (un nom désigne aussi ses descendants : « total » → « total.a »…). */
	fields: string[],
};

export type CertInfo = {
	subject: string,
	/**  Nom commun et organisation du titulaire. */
	commonName: string | null,
	organization: string | null,
	issuer: string,
	issuerName: string | null,
	/**  Validité (secondes Unix). */
	notBefore: number,
	notAfter: number,
	serial: string,
	/**  Empreinte SHA-256 (« 4F:2A:… »). */
	sha256: string,
	/**  Certificats de la chaîne, du signataire vers la racine (noms communs). */
	chain: string[],
	/**  Haut de la chaîne (racine, ou dernier certificat trouvé) : autorité à approuver. */
	rootName: string,
	rootSha256: string,
};

/**
 *  Tour précédent de la conversation, renvoyé à chaque question (l'agent ne garde pas
 *  de session).
 */
export type ChatTurn = {
	/**  « user » ou « assistant ». */
	role: string,
	text: string,
};

export type CheckStyle = "check" | "cross" | "dot";

export type ChoiceOption = {
	/**  Valeur exportée (`/V`). */
	value: string,
	/**  Libellé affiché. */
	label: string,
};

/**  Résultat de la détection, pour les préférences. */
export type Detected = {
	path: string | null,
	version: string | null,
	/**  Installation trouvée mais trop ancienne (options inconnues). */
	outdated: OutdatedAgent | null,
};

export type DocInfo = {
	id: number,
	path: string,
	name: string,
	title: string | null,
	pages: PageGeom[],
	encrypted: boolean,
	form: FormKind,
	signatureCount: number,
	canCopy: boolean,
	canPrint: boolean,
};

/**  État d'édition renvoyé à l'interface après chaque opération. */
export type EditState = {
	annots: Annot[],
	/**  Champs du formulaire AcroForm (vide sans formulaire). */
	fields: FormField[],
	/**  Pages dont le rendu a changé depuis l'état précédent. */
	changedPages: number[],
	canUndo: boolean,
	canRedo: boolean,
	dirty: boolean,
	/**  Des zones de caviardage seront appliquées à l'enregistrement. */
	pendingRedactions: boolean,
	/**  Nombre d'annotations ajoutées, modifiées ou supprimées depuis l'enregistrement. */
	unsavedCount: number,
	/**  Auteur des nouvelles annotations (« Vous » dans la liste). */
	author: string,
	/**  Nouvelle géométrie des pages quand leur nombre, leur ordre ou leur rotation a changé. */
	pages: PageGeom[] | null,
};

export type ExportFormat = 
/**  Annotations et champs restent modifiables. */
"pdf" | 
/**  Annotations et champs fusionnés dans la page. */
"flattened" | "png" | "jpg";

export type ExportOptions = {
	format: ExportFormat,
	quality: Quality,
	/**  Pages exportées (indices) ; `None` : toutes. */
	pages: number[] | null,
	/**  Résolution d'un export en images (points par pouce). */
	dpi: number,
	protection: ExportProtection | null,
};

export type ExportProtection = {
	password: string,
	allowPrint: boolean,
	allowCopy: boolean,
};

export type ExportResult = {
	/**  Fichiers écrits (vide pour une estimation). */
	files: string[],
	/**  Taille totale en octets. */
	size: number,
};

/**  Mise en forme d'un champ texte (actions `/F` et `/K`). */
export type FieldFormat = 
/**
 *  `AFNumber_*` : `sep_style` 0 « 1,234.56 », 1 « 1234.56 », 2 « 1.234,56 », 3 « 1234,56 »,
 *  4 « 1'234.56 » ; `neg_style` 0 « - », 1 rouge, 2 parenthèses, 3 parenthèses et rouge.
 */
{ type: "number"; decimals: number; sepStyle: number; negStyle: number; currency: string; prepend: boolean } | 
/**  `AFPercent_*` : la valeur 0,15 s'affiche « 15 % ». */
{ type: "percent"; decimals: number; sepStyle: number } | 
/**  `AFDate_*` : format Acrobat (`dd/mm/yyyy`, `mmm d, yyyy`…). */
{ type: "date"; format: string } | 
/**  `AFTime_*` : `HH:MM`, `h:MM tt`… */
{ type: "time"; format: string } | 
/**
 *  `AFSpecial_*` : 0 code postal, 1 code postal + 4, 2 téléphone, 3 numéro de sécurité
 *  sociale (États-Unis). La valeur ne garde que les chiffres.
 */
{ type: "special"; kind: number } | 
/**
 *  `AFSpecial_KeystrokeEx` : masque (9 chiffre, A lettre, O lettre ou chiffre, X tout
 *  caractère, le reste littéral). La valeur est stockée mise en forme.
 */
{ type: "mask"; mask: string };

export type FieldKind = { type: "text"; multiline: boolean; password: boolean; 
/**  Cases régulières (`/MaxLen` caractères répartis sur la largeur). */
comb: boolean; maxLen: number | null } | { type: "checkbox" } | { type: "radio" } | { type: "combo"; options: ChoiceOption[]; 
/**  Saisie libre autorisée. */
editable: boolean } | { type: "list"; options: ChoiceOption[]; multi: boolean } | 
/**  Champ de signature (phase 4) : affiché, non rempli ici. */
{ type: "signature" } | 
/**  Bouton poussoir : sans valeur. */
{ type: "button" };

export type FontFamily = 
/**  Helvetica */
"sans" | 
/**  Times-Roman */
"serif" | 
/**  Courier */
"mono";

export type FormField = {
	/**  Nom complet du champ (`a.b.c`), unique. */
	id: string,
	/**  Info-bulle (`/TU`). */
	label: string | null,
	kind: FieldKind,
	/**  Texte : `[texte]` ; case ou radio : `[état coché]` ou `[]` ; liste : valeurs choisies. */
	value: string[],
	/**  Valeur par défaut (`/DV`), rétablie par « Effacer le formulaire ». */
	defaultValue: string[],
	readOnly: boolean,
	required: boolean,
	/**  Taille du texte (0 = automatique). */
	fontSize: number,
	/**  Alignement (`/Q`) : 0 gauche, 1 centre, 2 droite. */
	align: number,
	font: FontFamily,
	widgets: Widget[],
	/**  Mise en forme, plage autorisée et calcul (fonctions standard d'Acrobat). */
	format: FieldFormat | null,
	range: RangeRule | null,
	calc: Calculation | null,
	/**  Le champ a des scripts personnalisés, non exécutés. */
	customScript: boolean,
};

export type FormKind = "none" | "acroForm" | 
/**  XFA dynamique : non pris en charge (message clair dans l'UI). */
"xfa";

/**  Image importée pour un tampon. */
export type ImageInfo = {
	key: string,
	width: number,
	height: number,
};

export type LanguagePref = "system" | "fr" | "en";

export type LinkInfo = {
	rect: Rect,
	target: LinkTarget,
};

export type LinkTarget = { type: "page"; page: number } | { type: "uri"; uri: string };

export type OmarchyTheme = {
	/**  Nom du thème (« tokyo-night »). */
	name: string,
	/**  Thème sombre (`mode`, ou absence de `light.mode`) ; `None` : à déduire du fond. */
	dark: boolean | null,
	/**  Couleurs de `colors.toml` (« #rrggbb »), par nom de clé. */
	colors: { [key in string]: string },
};

/**  Le thème d'Omarchy a changé (ou a disparu). */
export type OmarchyThemeEvent = {
	theme: OmarchyTheme | null,
};

/**  Fichiers à ouvrir reçus pendant l'exécution (seconde instance, association de fichiers). */
export type OpenFilesEvent = {
	paths: string[],
};

export type OutdatedAgent = {
	path: string,
	version: string | null,
};

export type OutlineItem = {
	title: string,
	/**  Page cible (index 0) si la destination est locale. */
	page: number | null,
	children: OutlineItem[],
};

export type PageGeom = {
	/**  Largeur affichée en points (rotation appliquée). */
	width: number,
	height: number,
	/**  Libellé de page (`/PageLabels`), ex. « iv ». */
	label: string | null,
};

/**  Opération sur les pages (indices de pages dans l'ordre courant, à partir de 0). */
export type PageOp = 
/**  Déplace les pages avant la page d'indice `to` (`to` = nombre de pages : à la fin). */
{ op: "move"; pages: number[]; to: number } | 
/**  Rotation de ±90° (multiple de 90). */
{ op: "rotate"; pages: number[]; delta: number } | { op: "delete"; pages: number[] } | 
/**  Chaque copie suit sa page d'origine. */
{ op: "duplicate"; pages: number[] } | 
/**  Page blanche au format de la page précédente, insérée à l'indice `at`. */
{ op: "insertBlank"; at: number } | 
/**  Copie de pages d'un autre document (ou du même) à l'indice `at`. */
{ op: "import"; from: number; pages: number[]; at: number };

export type PageText = {
	runs: TextRun[],
};

export type PdfError = { kind: "passwordRequired" } | { kind: "wrongPassword" } | { kind: "notFound"; message: string } | { kind: "invalid"; message: string } | { kind: "unknownDocument" } | { kind: "pageOutOfRange" } | { kind: "cancelled" } | { kind: "engine"; message: string };

export type Point = {
	x: number,
	y: number,
};

/**  Qualité des images : recompression des images du PDF, ou qualité JPEG d'un export en images. */
export type Quality = 
/**  Fichier le plus léger. */
"light" | "balanced" | 
/**  Images d'origine. */
"max";

/**  `AFRange_Validate` (bornes incluses). */
export type RangeRule = {
	min: number | null,
	max: number | null,
};

export type RecentDoc = {
	path: string,
	name: string,
	/**  Horodatage d'ouverture (ms depuis l'époque Unix). */
	openedAt: number,
	pageCount: number,
	locked: boolean,
	signed: boolean,
	form: boolean,
	/**  Identifiant de la miniature (servie par `lunas-pdf://localhost/thumb/<id>.png`). */
	thumb: string | null,
};

export type RecentsView = "grid" | "list";

export type Rect = {
	x: number,
	y: number,
	w: number,
	h: number,
};

/**  Signature manuscrite enregistrée (planche 07) : image PNG à fond transparent. */
export type SavedSignature = SavedSignature_Serialize | SavedSignature_Deserialize;

/**  Signature manuscrite enregistrée (planche 07) : image PNG à fond transparent. */
export type SavedSignature_Deserialize = {
	id: string,
	/**  Date d'ajout (millisecondes Unix). */
	created: number,
	width: number,
	height: number,
	/**  Image en `data:image/png;base64,…` (renseignée à la lecture, jamais stockée). */
	data?: string,
};

/**  Signature manuscrite enregistrée (planche 07) : image PNG à fond transparent. */
export type SavedSignature_Serialize = {
	id: string,
	/**  Date d'ajout (millisecondes Unix). */
	created: number,
	width: number,
	height: number,
	/**  Image en `data:image/png;base64,…` (renseignée à la lecture, jamais stockée). */
	data?: string,
};

export type SearchEvent = 
/**  Résultats d'une page (envoyé même vide pour la progression). */
{ type: "page"; searchId: number; page: number; hits: SearchHit[] } | { type: "done"; searchId: number; total: number };

export type SearchHit = {
	page: number,
	/**  Une boîte par ligne couverte par l'occurrence. */
	rects: Rect[],
	before: string,
	matched: string,
	after: string,
};

export type Settings = {
	theme?: ThemePref,
	/**  Couleur d'accent CSS (#rrggbb). */
	accent?: string,
	language?: LanguagePref,
	/**  Boutons Réduire/Agrandir/Fermer dans la barre de titre (à masquer sous un WM en tiling). */
	windowControls?: boolean,
	recentsView?: RecentsView,
	sidebarOpen?: boolean,
	/**  Nom d'auteur des annotations (vide : nom de l'utilisateur du système). */
	authorName?: string,
	/**  Fond teinté sur les champs de formulaire (bandeau de la planche 04). */
	highlightFields?: boolean,
	/**  Documents signés pour lesquels l'avertissement avant modification est désactivé. */
	signedOk?: string[],
	/**  Agent du panneau IA (aucun : panneau masqué). */
	aiAgent?: Agent,
	/**  Chemin de l'agent saisi à la main ; vide : détection automatique. */
	aiPath?: string,
	/**  Modèle (ex. « sonnet ») ; vide : celui de l'agent. */
	aiModel?: string,
};

export type SigStatus = 
/**  Intacte et certificat reconnu. */
"valid" | 
/**  Le contenu signé a été modifié, ou la signature est fausse. */
"invalid" | 
/**  Intacte, mais le certificat n'est pas reconnu par ce système (ou hors validité). */
"unknown";

export type SignatureInfo = {
	/**  Nom du champ de signature. */
	field: string,
	/**  Emplacement visible (absent pour une signature invisible). */
	page: number | null,
	rect: Rect | null,
	status: SigStatus,
	/**  Nom du signataire (certificat, sinon `/Name`). */
	signer: string | null,
	organization: string | null,
	/**  Date de signature (secondes Unix) et décalage horaire déclaré, en minutes. */
	signedAt: number | null,
	utcOffset: number | null,
	reason: string | null,
	location: string | null,
	/**  Empreinte et signature correctes. */
	intact: boolean,
	/**  La signature couvre tout le fichier (sinon : révisions ajoutées après signature). */
	coversWhole: boolean,
	/**  Chaîne de certificats jusqu'à une autorité reconnue. */
	trusted: boolean,
	/**  Origine de cette reconnaissance : « system », « user », « eu:IT », « microsoft ». */
	trustSource: string | null,
	/**  Certificat valide à la date de signature. */
	certValidAtSigning: boolean,
	/**  Horodatage : date (secondes Unix) et vérification de son jeton. */
	timestamp: number | null,
	timestampVerified: boolean,
	/**  Autorité d'horodatage reconnue par le système. */
	timestampTrusted: boolean,
	certificate: CertInfo | null,
	subFilter: string | null,
	/**  Cause d'un échec de vérification. */
	problem: string | null,
};

/**
 *  Fragment de texte pour la couche de sélection : un mot (ou une suite de glyphes contigus)
 *  sur une même ligne.
 */
export type TextRun = {
	text: string,
	rect: Rect,
	/**  Dernier fragment de sa ligne (l'UI insère un saut de ligne pour la copie). */
	eol: boolean,
};

/**  Sélection de texte pour les outils de marquage : une boîte par ligne. */
export type TextSelection = {
	rects: Rect[],
	text: string,
};

export type ThemePref = "system" | "light" | "dark";

/**  État des listes de confiance (UE, Microsoft) utilisées pour vérifier les signatures. */
export type TrustListsInfo = {
	/**  Date de génération (millisecondes Unix). */
	generated: number,
	eu: number,
	microsoft: number,
};

/**  Listes de confiance mises à jour : les signatures ouvertes sont à revérifier. */
export type TrustListsUpdatedEvent = {
	generated: number,
};

/**  Autorité de certification approuvée par l'utilisateur pour vérifier les signatures. */
export type TrustedRoot = {
	/**  Empreinte SHA-256 (« 4F:2A:… »), aussi nom du fichier. */
	id: string,
	name: string,
	/**  Date d'ajout (millisecondes Unix). */
	added: number,
};

export type Widget = {
	page: number,
	/**  Rectangle d'affichage (points, repère de la page affichée). */
	rect: Rect,
	/**  Nom de l'état « coché » (cases et radios). */
	onState: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

