// Généré par tauri-specta — ne pas modifier.
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Ouvre un document. Sans mot de passe, essaie celui mémorisé dans le trousseau.
	 *  `remember` mémorise le mot de passe fourni s'il est correct.
	 */
	openDocument: (path: string, password: string | null, remember: boolean) => typedError<DocInfo, PdfError>(__TAURI_INVOKE("open_document", { path, password, remember })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	closeDocument: (doc: number) => __TAURI_INVOKE<void>("close_document", { doc }),
	/**  Abandonne les rendus en attente d'une époque antérieure (défilement rapide, zoom). */
	setRenderEpoch: (doc: number, epoch: number) => __TAURI_INVOKE<void>("set_render_epoch", { doc, epoch }),
	getOutline: (doc: number) => typedError<OutlineItem[], PdfError>(__TAURI_INVOKE("get_outline", { doc })),
	/**  Modèle d'annotations du document (chargé à la demande). */
	loadAnnotations: (doc: number) => typedError<EditState, PdfError>(__TAURI_INVOKE("load_annotations", { doc })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})}))}) } : v) as typeof v)),
	/**  Applique des opérations (ajout, modification, suppression) en une seule étape d'annulation. */
	applyAnnotations: (doc: number, ops: AnnotOp[]) => typedError<EditState, PdfError>(__TAURI_INVOKE("apply_annotations", { doc, ops })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})}))}) } : v) as typeof v)),
	undo: (doc: number) => typedError<EditState, PdfError>(__TAURI_INVOKE("undo", { doc })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})}))}) } : v) as typeof v)),
	redo: (doc: number) => typedError<EditState, PdfError>(__TAURI_INVOKE("redo", { doc })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})}))}) } : v) as typeof v)),
	/**  Masque une annotation pendant son édition en place (hors historique). */
	setAnnotationHidden: (doc: number, id: string, hidden: boolean) => typedError<EditState, PdfError>(__TAURI_INVOKE("set_annotation_hidden", { doc, id, hidden })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,annots:v.data.annots.map(i=>i),fields:v.data.fields.map(i=>({...i,range:i.range==null?i.range:({...i.range,min:i.range.min==null?i.range.min:i.range.min,max:i.range.max==null?i.range.max:i.range.max})}))}) } : v) as typeof v)),
	/**  Boîtes des lignes de texte entre deux points (outils de marquage). */
	textRange: (doc: number, page: number, from: Point, to: Point) => typedError<TextSelection, PdfError>(__TAURI_INVOKE("text_range", { doc, page, from, to })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,rects:v.data.rects.map(i=>i)}) } : v) as typeof v)),
	importImage: (doc: number, path: string) => typedError<ImageInfo, PdfError>(__TAURI_INVOKE("import_image", { doc, path })),
	/**  Copie une image importée d'un document à l'autre (collage d'un tampon image). */
	copyImage: (from: number, to: number, key: string) => typedError<null, PdfError>(__TAURI_INVOKE("copy_image", { from, to, key })),
	/**
	 *  Enregistre le document (sur place, ou sous `path`). Écriture atomique ; l'original n'est
	 *  jamais touché avant cet appel.
	 */
	saveDocument: (doc: number, path: string | null) => typedError<DocInfo, PdfError>(__TAURI_INVOKE("save_document", { doc, path })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,pages:v.data.pages.map(i=>i)}) } : v) as typeof v)),
	getLinks: (doc: number, page: number) => typedError<LinkInfo[], PdfError>(__TAURI_INVOKE("get_links", { doc, page })),
	getPageText: (doc: number, page: number) => typedError<PageText, PdfError>(__TAURI_INVOKE("get_page_text", { doc, page })),
	/**  Recherche plein texte ; les résultats arrivent page par page sur `on_event`. */
	search: (doc: number, searchId: number, query: string, caseSensitive: boolean, onEvent: Channel<SearchEvent>) => __TAURI_INVOKE<void>("search", { doc, searchId, query, caseSensitive, onEvent }),
	cancelSearch: (doc: number) => __TAURI_INVOKE<void>("cancel_search", { doc }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSettings: (settings: Settings) => typedError<null, PdfError>(__TAURI_INVOKE("set_settings", { settings })),
	getRecents: () => __TAURI_INVOKE<RecentDoc[]>("get_recents").then((v) => (v.map(i=>i) as typeof v)),
	removeRecent: (path: string) => typedError<null, PdfError>(__TAURI_INVOKE("remove_recent", { path })),
	clearRecents: () => typedError<null, PdfError>(__TAURI_INVOKE("clear_recents")),
	/**  Langue de l'OS (ex. « fr-FR »). */
	systemLocale: () => __TAURI_INVOKE<string>("system_locale"),
	/**  Fichiers passés en ligne de commande au lancement (vidé à la lecture). */
	takePendingFiles: () => __TAURI_INVOKE<string[]>("take_pending_files"),
	/**
	 *  Erreurs JavaScript de l'interface, recopiées dans le terminal (diagnostic sous WebKitGTK,
	 *  dont la console n'est pas visible).
	 */
	logFrontendError: (message: string) => __TAURI_INVOKE<void>("log_frontend_error", { message }),
};

/** Events */
export const events = {
	openFilesEvent: makeEvent<OpenFilesEvent>("open-files-event"),
};

/* Types */
export type Annot = {
	/**  Identifiant stable (`/NM` si présent, sinon généré). */
	id: string,
	page: number,
	rect: Rect,
	/**  Couleur « #rrggbb ». */
	color: string,
	/**  Opacité 0–1 (`/CA`). */
	opacity: number,
	/**  Épaisseur du trait en points. */
	width: number,
	/**  Commentaire associé (`/Contents`). */
	contents: string | null,
	author: string | null,
	/**  Date de modification (`/M`, format PDF). */
	modified: string | null,
	/**  Texte recouvert (surlignage, soulignement…), calculé pour la liste. */
	excerpt: string | null,
	body: AnnotBody,
	/**  Masquée le temps d'une édition en place (jamais enregistrée). */
	hidden?: boolean,
};

export type AnnotBody = { type: "highlight"; quads: Rect[] } | { type: "underline"; quads: Rect[] } | { type: "strikeOut"; quads: Rect[] } | { type: "freeText"; text: string; font: FontFamily; size: number } | 
/**  Note (annotation /Text) : icône sur la page, texte dans `contents`. */
{ type: "note" } | { type: "square" } | { type: "circle" } | { type: "line"; from: Point; to: Point; arrow: boolean } | { type: "check"; style: CheckStyle } | 
/**  Tampon image ; `image` identifie l'image importée (ou l'apparence existante). */
{ type: "image"; image: string } | 
/**  Zone à caviarder : le contenu sous les zones est supprimé à l'enregistrement. */
{ type: "redact"; quads: Rect[] } | 
/**  Annotation existante non éditable (Ink, Polygon, tampon externe…) : déplacer ou supprimer. */
{ type: "other"; subtype: string };

/**  Opération élémentaire sur les annotations (pattern commande). */
export type AnnotOp = 
/**  `index` : position d'insertion (utilisée pour annuler une suppression). */
{ op: "add"; annot: Annot; index: number | null } | { op: "update"; annot: Annot } | { op: "remove"; id: string } | 
/**  Valeur d'un champ de formulaire (voir `FormField::value`). */
{ op: "setField"; id: string; value: string[] };

export type CalcOp = "sum" | "product" | "average" | "min" | "max";

/**  `AFSimple_Calculate`. */
export type Calculation = {
	op: CalcOp,
	/**  Noms de champs (un nom désigne aussi ses descendants : « total » → « total.a »…). */
	fields: string[],
};

export type CheckStyle = "check" | "cross" | "dot";

export type ChoiceOption = {
	/**  Valeur exportée (`/V`). */
	value: string,
	/**  Libellé affiché. */
	label: string,
};

export type DocInfo = {
	id: number,
	path: string,
	name: string,
	title: string | null,
	pages: PageGeom[],
	encrypted: boolean,
	form: FormKind,
	signatureCount: number,
	canCopy: boolean,
	canPrint: boolean,
};

/**  État d'édition renvoyé à l'interface après chaque opération. */
export type EditState = {
	annots: Annot[],
	/**  Champs du formulaire AcroForm (vide sans formulaire). */
	fields: FormField[],
	/**  Pages dont le rendu a changé depuis l'état précédent. */
	changedPages: number[],
	canUndo: boolean,
	canRedo: boolean,
	dirty: boolean,
	/**  Des zones de caviardage seront appliquées à l'enregistrement. */
	pendingRedactions: boolean,
	/**  Nombre d'annotations ajoutées, modifiées ou supprimées depuis l'enregistrement. */
	unsavedCount: number,
	/**  Auteur des nouvelles annotations (« Vous » dans la liste). */
	author: string,
};

/**  Mise en forme d'un champ texte (actions `/F` et `/K`). */
export type FieldFormat = 
/**
 *  `AFNumber_*` : `sep_style` 0 « 1,234.56 », 1 « 1234.56 », 2 « 1.234,56 », 3 « 1234,56 »,
 *  4 « 1'234.56 » ; `neg_style` 0 « - », 1 rouge, 2 parenthèses, 3 parenthèses et rouge.
 */
{ type: "number"; decimals: number; sepStyle: number; negStyle: number; currency: string; prepend: boolean } | 
/**  `AFPercent_*` : la valeur 0,15 s'affiche « 15 % ». */
{ type: "percent"; decimals: number; sepStyle: number } | 
/**  `AFDate_*` : format Acrobat (`dd/mm/yyyy`, `mmm d, yyyy`…). */
{ type: "date"; format: string } | 
/**  `AFTime_*` : `HH:MM`, `h:MM tt`… */
{ type: "time"; format: string } | 
/**
 *  `AFSpecial_*` : 0 code postal, 1 code postal + 4, 2 téléphone, 3 numéro de sécurité
 *  sociale (États-Unis). La valeur ne garde que les chiffres.
 */
{ type: "special"; kind: number } | 
/**
 *  `AFSpecial_KeystrokeEx` : masque (9 chiffre, A lettre, O lettre ou chiffre, X tout
 *  caractère, le reste littéral). La valeur est stockée mise en forme.
 */
{ type: "mask"; mask: string };

export type FieldKind = { type: "text"; multiline: boolean; password: boolean; 
/**  Cases régulières (`/MaxLen` caractères répartis sur la largeur). */
comb: boolean; maxLen: number | null } | { type: "checkbox" } | { type: "radio" } | { type: "combo"; options: ChoiceOption[]; 
/**  Saisie libre autorisée. */
editable: boolean } | { type: "list"; options: ChoiceOption[]; multi: boolean } | 
/**  Champ de signature (phase 4) : affiché, non rempli ici. */
{ type: "signature" } | 
/**  Bouton poussoir : sans valeur. */
{ type: "button" };

export type FontFamily = 
/**  Helvetica */
"sans" | 
/**  Times-Roman */
"serif" | 
/**  Courier */
"mono";

export type FormField = {
	/**  Nom complet du champ (`a.b.c`), unique. */
	id: string,
	/**  Info-bulle (`/TU`). */
	label: string | null,
	kind: FieldKind,
	/**  Texte : `[texte]` ; case ou radio : `[état coché]` ou `[]` ; liste : valeurs choisies. */
	value: string[],
	/**  Valeur par défaut (`/DV`), rétablie par « Effacer le formulaire ». */
	defaultValue: string[],
	readOnly: boolean,
	required: boolean,
	/**  Taille du texte (0 = automatique). */
	fontSize: number,
	/**  Alignement (`/Q`) : 0 gauche, 1 centre, 2 droite. */
	align: number,
	font: FontFamily,
	widgets: Widget[],
	/**  Mise en forme, plage autorisée et calcul (fonctions standard d'Acrobat). */
	format: FieldFormat | null,
	range: RangeRule | null,
	calc: Calculation | null,
	/**  Le champ a des scripts personnalisés, non exécutés. */
	customScript: boolean,
};

export type FormKind = "none" | "acroForm" | 
/**  XFA dynamique : non pris en charge (message clair dans l'UI). */
"xfa";

/**  Image importée pour un tampon. */
export type ImageInfo = {
	key: string,
	width: number,
	height: number,
};

export type LanguagePref = "system" | "fr" | "en";

export type LinkInfo = {
	rect: Rect,
	target: LinkTarget,
};

export type LinkTarget = { type: "page"; page: number } | { type: "uri"; uri: string };

/**  Fichiers à ouvrir reçus pendant l'exécution (seconde instance, association de fichiers). */
export type OpenFilesEvent = {
	paths: string[],
};

export type OutlineItem = {
	title: string,
	/**  Page cible (index 0) si la destination est locale. */
	page: number | null,
	children: OutlineItem[],
};

export type PageGeom = {
	/**  Largeur affichée en points (rotation appliquée). */
	width: number,
	height: number,
	/**  Libellé de page (`/PageLabels`), ex. « iv ». */
	label: string | null,
};

export type PageText = {
	runs: TextRun[],
};

export type PdfError = { kind: "passwordRequired" } | { kind: "wrongPassword" } | { kind: "notFound"; message: string } | { kind: "invalid"; message: string } | { kind: "unknownDocument" } | { kind: "pageOutOfRange" } | { kind: "cancelled" } | { kind: "engine"; message: string };

export type Point = {
	x: number,
	y: number,
};

/**  `AFRange_Validate` (bornes incluses). */
export type RangeRule = {
	min: number | null,
	max: number | null,
};

export type RecentDoc = {
	path: string,
	name: string,
	/**  Horodatage d'ouverture (ms depuis l'époque Unix). */
	openedAt: number,
	pageCount: number,
	locked: boolean,
	signed: boolean,
	form: boolean,
	/**  Identifiant de la miniature (servie par `feuillet://localhost/thumb/<id>.png`). */
	thumb: string | null,
};

export type RecentsView = "grid" | "list";

export type Rect = {
	x: number,
	y: number,
	w: number,
	h: number,
};

export type SearchEvent = 
/**  Résultats d'une page (envoyé même vide pour la progression). */
{ type: "page"; searchId: number; page: number; hits: SearchHit[] } | { type: "done"; searchId: number; total: number };

export type SearchHit = {
	page: number,
	/**  Une boîte par ligne couverte par l'occurrence. */
	rects: Rect[],
	before: string,
	matched: string,
	after: string,
};

export type Settings = {
	theme?: ThemePref,
	/**  Couleur d'accent CSS (#rrggbb). */
	accent?: string,
	language?: LanguagePref,
	/**  Boutons Réduire/Agrandir/Fermer dans la barre de titre (à masquer sous un WM en tiling). */
	windowControls?: boolean,
	recentsView?: RecentsView,
	sidebarOpen?: boolean,
	/**  Nom d'auteur des annotations (vide : nom de l'utilisateur du système). */
	authorName?: string,
	/**  Fond teinté sur les champs de formulaire (bandeau de la planche 04). */
	highlightFields?: boolean,
};

/**
 *  Fragment de texte pour la couche de sélection : un mot (ou une suite de glyphes contigus)
 *  sur une même ligne.
 */
export type TextRun = {
	text: string,
	rect: Rect,
	/**  Dernier fragment de sa ligne (l'UI insère un saut de ligne pour la copie). */
	eol: boolean,
};

/**  Sélection de texte pour les outils de marquage : une boîte par ligne. */
export type TextSelection = {
	rects: Rect[],
	text: string,
};

export type ThemePref = "system" | "light" | "dark";

export type Widget = {
	page: number,
	/**  Rectangle d'affichage (points, repère de la page affichée). */
	rect: Rect,
	/**  Nom de l'état « coché » (cases et radios). */
	onState: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

